name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version: [
          "1.7",
          "1.8.9",
          "1.9.4",
          "1.10.2",
          "1.11.2",
          "1.12.2",
          "1.13",
          "1.14",
          "1.15",
          "1.16",
          "1.17",
          "1.18",
          "22w19a",
          "1.19",
          "1.19.2",
          "1.20",
          "1.20.4",
          "1.20.5",
          "1.21"
        ]

    name: Build ${{ matrix.version }}
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate ${{ matrix.version }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :${{ matrix.version }}:runServer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-${{ matrix.version }}
          path: ${{ matrix.version }}/run/server/minecraft-data
          if-no-files-found: error
